pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',credentialsId: 'VinayMelmuri', url: 'https://github.com/VinayMelmuri/EmployeeManagementSystem.git'
            }
        }
        
        stage('Build') {
            steps {
				bat './mvnw.cmd clean install'
            }
        }

        stage('Liquibase Update') {
            steps {
                bat './mvnw.cmd liquibase:update'
            }
        }

        stage('Push Changes to GitHub') {
            steps {
                script {
                    def user = "VinayMelmuri"
                    def email = "vinaymelmuri@gmail.com"
                    
                    bat """
                    git config --global user.name '${user}'
                    git config --global user.email '${email}'
                    git add .
                    git commit -m "Automated update from Jenkins pipeline"
                    git push https://github.com/VinayMelmuri/EmployeeManagementSystem.git
                    """
                }
            }
        }
    }
}
