pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from Git
                git branch: 'main', url: 'https://github.com/VinayMelmuri/EmployeeManagementSystem.git'
            }
        }

        stage('Build') {
            steps {
                // Clean and build the application using Maven
                bat 'mvn clean install'
            }
        }

        stage('Liquibase Update') {
            steps {
                // Run Liquibase to apply database migrations
                bat 'mvn liquibase:update'
            }
        }

        stage('Run Tests') {
            steps {
                // Execute tests if applicable
                bat 'mvn test'
            }
        }

        stage('Package') {
            steps {
                // Package the application if necessary (e.g., create a JAR or WAR file)
                bat 'mvn package'
            }
        }


    }

    post {
        success {
            // Actions to perform if the pipeline succeeds
            echo 'Pipeline completed successfully!'
        }
        failure {
            // Actions to perform if the pipeline fails
            echo 'Pipeline failed. Please check the logs.'
        }
    }
}
